{
  "uuid": "7854782d-6c77-42cc-ab34-ee702f892ab7",
  "historyId": "c24f16e7e796aa8661902e57b8f8b29f",
  "status": "broken",
  "statusDetails": {
    "message": "`cy.visit()` failed trying to load:\n\nhttps://www.saucedemo.com/\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  > Error: getaddrinfo EAI_AGAIN www.saucedemo.com\n\nCommon situations why this would fail:\n  - you don't have internet access\n  - you forgot to run / boot your web server\n  - your web server isn't accessible\n  - you have weird network configuration settings on your computer",
    "trace": "CypressError: `cy.visit()` failed trying to load:\n\nhttps://www.saucedemo.com/\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  > Error: getaddrinfo EAI_AGAIN www.saucedemo.com\n\nCommon situations why this would fail:\n  - you don't have internet access\n  - you forgot to run / boot your web server\n  - your web server isn't accessible\n  - you have weird network configuration settings on your computer\n    at <unknown> (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:132367:74)\n    at visitFailedByErr (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:131757:12)\n    at <unknown> (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:132366:11)\n    at tryCatcher (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:1777:23)\n    at Promise._settlePromiseFromHandler (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:1489:31)\n    at Promise._settlePromise (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:1546:18)\n    at Promise._settlePromise0 (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:1591:10)\n    at Promise._settlePromises (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:1667:18)\n    at _drainQueueStep (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:2377:12)\nFrom previous event:\n    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:3456:19)\n    at Promise._then (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:1209:17)\n    at Promise._passThrough (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:4080:17)\n    at Promise.lastly.Promise.finally (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:4089:17)\n    at Object.onRunnableRun (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:163629:53)\n    at $Cypress.action (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:41559:28)\n    at Runnable.run (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:146211:13)\n    at next (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:155996:10)\n    at <unknown> (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:156040:5)\n    at timeslice (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:146551:27)\nFrom Your Spec Code:\n    at Context.eval (webpack://anst_cypress_project/./cypress/e2e/login.spec.cy.js:5:11)\n\nFrom Node.js Internals:\n  Error: getaddrinfo EAI_AGAIN www.saucedemo.com\n      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)"
  },
  "stage": "finished",
  "steps": [
    {
      "status": "failed",
      "statusDetails": {
        "message": "`cy.visit()` failed trying to load:\n\nhttps://www.saucedemo.com/\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  > Error: getaddrinfo EAI_AGAIN www.saucedemo.com\n\nCommon situations why this would fail:\n  - you don't have internet access\n  - you forgot to run / boot your web server\n  - your web server isn't accessible\n  - you have weird network configuration settings on your computer",
        "trace": "CypressError: `cy.visit()` failed trying to load:\n\nhttps://www.saucedemo.com/\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  > Error: getaddrinfo EAI_AGAIN www.saucedemo.com\n\nCommon situations why this would fail:\n  - you don't have internet access\n  - you forgot to run / boot your web server\n  - your web server isn't accessible\n  - you have weird network configuration settings on your computer\n    at <unknown> (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:132367:74)\n    at visitFailedByErr (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:131757:12)\n    at <unknown> (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:132366:11)\n    at tryCatcher (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:1777:23)\n    at Promise._settlePromiseFromHandler (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:1489:31)\n    at Promise._settlePromise (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:1546:18)\n    at Promise._settlePromise0 (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:1591:10)\n    at Promise._settlePromises (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:1667:18)\n    at _drainQueueStep (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:2377:12)\nFrom previous event:\n    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:3456:19)\n    at Promise._then (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:1209:17)\n    at Promise._passThrough (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:4080:17)\n    at Promise.lastly.Promise.finally (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:4089:17)\n    at Object.onRunnableRun (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:163629:53)\n    at $Cypress.action (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:41559:28)\n    at Runnable.run (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:146211:13)\n    at next (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:155996:10)\n    at <unknown> (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:156040:5)\n    at timeslice (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:146551:27)\nFrom Your Spec Code:\n    at Context.eval (webpack://anst_cypress_project/./cypress/e2e/login.spec.cy.js:5:11)\n\nFrom Node.js Internals:\n  Error: getaddrinfo EAI_AGAIN www.saucedemo.com\n      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)"
      },
      "stage": "finished",
      "steps": [
        {
          "status": "failed",
          "statusDetails": {},
          "stage": "finished",
          "steps": [],
          "attachments": [],
          "parameters": [],
          "start": 1745009908257,
          "name": "visit /",
          "stop": 1745009917853
        }
      ],
      "attachments": [],
      "parameters": [],
      "start": 1745009908075,
      "name": "\"before each\" hook",
      "stop": 1745009917854
    }
  ],
  "attachments": [],
  "parameters": [],
  "labels": [
    { "name": "package", "value": "cypress.e2e.login.spec.cy.js" },
    {
      "name": "suite",
      "value": "Login Test for Saucedemo Project with Multiple Users"
    }
  ],
  "links": [],
  "start": 1745009908065,
  "name": "Test for Successful Navigation to website",
  "fullName": "Test for Successful Navigation to website",
  "stop": 1745009917855
}
